# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'DouYUZhiBo-Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYUZhiBo-Swift

  target 'DouYUZhiBo-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYUZhiBo-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire'
pod 'Kingfisher'
end
